config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  get 'items/show'
  resources :feeds do
    member do
      resources :items, only: [:index, :show]
    end
  end

  root 'feeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :link, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :feed

  validates :link, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :feed_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :link, :description)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_feed, only: :index

  def index
    @items = @feed.items.order('date desc')
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feeds/_form.html.erb
 <div class="row justify-content-center">
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-7 col-md-offset-5 align-center field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="form-group col-md-7 col-md-offset-5 align-center field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="form-group col-md-7 col-md-offset-5 align-center field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="form-group col-md-7 col-md-offset-5 align-center actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<hr />

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing Feeds</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.link %></td>
        <td><%= feed.description %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>Create new Feed</h1>

<%= render 'form' %>

<hr />

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<h3> There are <%= link_to "#{@feed.items.count} items", items_path %> available for the feed <%= @feed.title %>
</h3>

<hr />

<%= link_to 'Edit', edit_feed_path %>
<%= link_to 'Back', feeds_path %>

app/views/items/index.html.erb
<h1>Links for Feed - <%= @feed.title %></h1>
<% @items.each do |item| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= link_to item.title, item %> - <i> published <%= time_ago_in_words(item.date) %> ago.</i>
    </div>
  </div>
<% end %>
<hr />
<%= link_to 'Back', feed_path %>

app/views/items/show.html.erb
<h3><%= link_to @item.title, @item.link %></h3>
<div>
  <i>published on <%= @item.date %></i>
  <p>
    <%= @item.description.html_safe %>
  </p>
</div>
<hr />
<%= link_to 'Back', url_for(:back) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RssReader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h2 id="notice"><%= notice %></h2>
      <hr />
      <%= yield %>
    </div>
  </body>
</html>